package org.elako.idleprison.items.materiales;

public enum IpMateriales {
    MENU, AIRE, MADERA_INFIERNO, MADERA_INFIERNO_CALIDAD, TABLONES_QUEMADOS, TABLONES_INFERNALES, PICO_MADERA, CALCITA, POLVO_HUESO, ALGA,
    ALGA_BLOQUE, PIEDRA_INFIERNO, PIEDRA_INFIERNO_ROJA, PIEDRA_INFIERNO_VERDE, BLOQUE_MAGMATICO, BAYA_LUMINOSA, HIELO,
    FRAGMENTO_AZUL1, ESENCIA_AZUL1, PESCADO_CRUDO, PESCADO_BRASA, PEZ_GLOBO, ELEMENTO, RESTOS_BASURA,
    CALCITA_ANTIGUA, PODREDUMBRE, RESTOS_COMIDA1, RESTOS_COMIDA2, CASCO_ELEMENTAL, PECHERA_ELEMENTAL,
    PANTALONES_ELEMENTALES, BOTAS_ELEMENTALES, MADERA_ROBLE, TABLONES_ROBLE, PICO_PIEDRA, PIEDRA, ROCA, ROCA_ARENOSA,
    ARENA, LENTE, RODAJA_SANDIA, SANDIA, CASCO_SANDIA, PECHERA_SANDIA, PANTALONES_SANDIA, BOTAS_SANDIA,  FRAGMENTO_ROJO1,
    ESENCIA_ROJA1, GRANITO, GRAN_GRANITO, FLOR_DESIERTO, DESIERTO_ROJO, CASCO_DESERTICO, PECHERA_DESERTICA,
    PANTALONES_DESERTICOS, BOTAS_DESERTICAS, FRAGMENTO_VERDE1, ESENCIA_VERDE1, FRAGMENTO_AZUL2, ESENCIA_AZUL2,
    CATALEJO, ARENISCA, CUARZO, TRIGO, BALA_TRIGO, PAN, MINI_ROCA, CARBON, MENA_CARBON, FRAGMENTO_AMARILLO1,
    ESENCIA_AMARILLA1, DETECTOR1, HIELO_COMPACTO, SALMON_CRUDO, SALMON_AHUMADO, MENA_HIERRO, LINGOTE_HIERRO, PICO_HIERRO,
    CASCO_HIERRO, PECHERA_HIERRO, PANTALONES_HIERRO, BOTAS_HIERRO, ARBUSTO, HOJAS, MANZANA, DIORITA, GRAN_DIORITA, NIEVE,
    MENA_CARBON_OSCURA, AMATISTA, MENA_STYLUM, STYLUM, PIEDRA_LUNAR, AMATISTA_CRISTAL , FRAGMENTO_ROJO2, ESENCIA_ROJA2,
    FRAGMENTO_VERDE2, ESENCIA_VERDE2, FRAGMENTO_NEGRO1, ESENCIA_NEGRA1

}
