name: elako
version: '1.0-SNAPSHOT'
main: me.elako.elako.Elako
api-version: 1.18
commands:
  inmolar:
    aliases: [inmolar]
    description: para explotar con tamaño n /inmolar (n)
  ubicacion:
      aliases: [ubicacion]
  generador:
    aliases: [generador]
    description: para generar un spawner en tu ubicación /generador
